name: daleel_naw3ya
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0 # تأكد من وجود الإصدار
  icons_launcher: ^3.0.0
  flutter_bloc: any
  icons_plus: any
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  dots_indicator: ^4.0.1
  cached_network_image: ^3.4.1
  bloc: any
  retrofit: any
  json_annotation: any
  dio: any
  pretty_dio_logger: any
  cherry_toast: ^1.13.0
  get_it: any
  animate_do: any
  injectable: any
  shared_preferences: any
  shimmer: ^3.0.0
  animated_bottom_navigation_bar: any
  cached_video_player_plus: any
  maps_launcher: any
  card_animation_hover: any
  introduction_screen: ^4.0.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_login: ^6.0.0
  image_picker: ^1.2.1
  google_generative_ai: 0.4.0
  http: ^1.1.0
  url_launcher: ^6.3.1
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_messaging: any
  flutter_local_notifications: any
  firebase_notifications_handler: any
  flutter_fcm: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  injectable_generator: any
  json_serializable: any
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Cairo
      fonts:
        - asset: lib/assets/font/Cairo-Regular.ttf
        - asset: lib/assets/font/Cairo-Bold.ttf
          weight: 700

  assets:
    - lib/assets/images/

# --- إعدادات أيقونة التطبيق (App Icon) ---
icons_launcher:
  image_path: "lib/assets/images/codeare.png"
  platforms:
    android:
      enable: true
      image_path: "lib/assets/images/codeare.png"
    ios:
      enable: true
      image_path: "lib/assets/images/codeare.png"

# --- إعدادات شاشة البداية (Splash Screen) ---
flutter_native_splash:
  color: "#292F91" # لون الخلفية (نفس لون الأب بار بتاعك)
  image: "lib/assets/images/codeare.png"
  android_12:
    image: "lib/assets/images/codeare.png"
    color: "#292F91"
  fullscreen: true